[[Xorg_libXfixes]]
arch = "aarch64"
git-tree-sha1 = "2d144f4299e0693688706c0f9b7d2b88786edff2"
libc = "glibc"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "12529100f09f9799504ce46324625c1dea9bb85debd4a63a75e1475d1040f507"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.1+0/Xorg_libXfixes.v6.0.1.aarch64-linux-gnu.tar.gz"
[[Xorg_libXfixes]]
arch = "aarch64"
git-tree-sha1 = "cc27a9dcfe446c5719081a40ba7bf89927556eeb"
libc = "musl"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "6e346e6debbe69da72984228fac69584ee981b170d9be67521d6e064984f181c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.1+0/Xorg_libXfixes.v6.0.1.aarch64-linux-musl.tar.gz"
[[Xorg_libXfixes]]
arch = "aarch64"
git-tree-sha1 = "f2d74ec25fc5cffdb2b96b024f3e83e5ed9eea1f"
os = "freebsd"

    [[Xorg_libXfixes.download]]
    sha256 = "8ba1b5a8e1ffa5905b8a142a9682dca279d2b907afeff588417473c882f4f3de"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.1+0/Xorg_libXfixes.v6.0.1.aarch64-unknown-freebsd.tar.gz"
[[Xorg_libXfixes]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "220abb52020655eabcb966f971dc8e0699aeaa5c"
libc = "glibc"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "a0a8f866f7d755184c86632b93c090a005aa336a2efde75dd605e7ef3632a2fc"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.1+0/Xorg_libXfixes.v6.0.1.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_libXfixes]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ef946c6aec506dc15c28bd422723bf773ad0b1f7"
libc = "musl"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "712f0eaefd823d94aa05b765cfaf2bb87aa9eb17f14d2489756c81abe7873d47"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.1+0/Xorg_libXfixes.v6.0.1.armv6l-linux-musleabihf.tar.gz"
[[Xorg_libXfixes]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e4cffa32bd2906d748457b2e6e7808ad7f984505"
libc = "glibc"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "b00a51f0bf664484d7bceb40ae234ba786faef33402c9d9034150c56364935a2"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.1+0/Xorg_libXfixes.v6.0.1.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXfixes]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4ec3495725ad4d655716e9b5d0074e7de05c8e7d"
libc = "musl"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "c7278ab2b90a4bde98cafed8270156c7318120bc6bd2eebb72063bdc1dacd64c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.1+0/Xorg_libXfixes.v6.0.1.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libXfixes]]
arch = "i686"
git-tree-sha1 = "2d6ec83860aba59790ad3095d6c2b12c237d5c19"
libc = "glibc"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "c09fc17997153da3df641ad27bac5d704c060d627a7c0dbeb127706d2c9b975f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.1+0/Xorg_libXfixes.v6.0.1.i686-linux-gnu.tar.gz"
[[Xorg_libXfixes]]
arch = "i686"
git-tree-sha1 = "16322a33fcd4a3db3804bab9da04000eb23e10d5"
libc = "musl"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "ca9280d3b91e50176b20b9e9a438316f326c4dde31ba461023a40e4ff82371ef"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.1+0/Xorg_libXfixes.v6.0.1.i686-linux-musl.tar.gz"
[[Xorg_libXfixes]]
arch = "powerpc64le"
git-tree-sha1 = "445416a3b760c260a76459fc53dd33628f136b6f"
libc = "glibc"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "24316cb46c28eaa8310e8e9f26b44eb5cfc2aaa95f90d2b8cf2d66283380aa66"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.1+0/Xorg_libXfixes.v6.0.1.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libXfixes]]
arch = "riscv64"
git-tree-sha1 = "ab830b4dee1b895ebe2463f3aef00835836e1edd"
libc = "glibc"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "4f4a7ff9369ec3481056cda92c571178832e78f927e54b2e3b5b32d617911174"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.1+0/Xorg_libXfixes.v6.0.1.riscv64-linux-gnu.tar.gz"
[[Xorg_libXfixes]]
arch = "x86_64"
git-tree-sha1 = "65c5e10af6182e66ace3d62ab4d99114f9009e7e"
libc = "glibc"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "abd265e7093ca694b63d8a0732d346b8fcfa9bff010c6aae2f5a4936d5cadc77"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.1+0/Xorg_libXfixes.v6.0.1.x86_64-linux-gnu.tar.gz"
[[Xorg_libXfixes]]
arch = "x86_64"
git-tree-sha1 = "dc5f1b475d7ebcd77d695068695e3c98922e4aae"
libc = "musl"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "b83f26a2739b9ea138582d51a1f0e9e5266214367984b6e1b772914e62f300d1"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.1+0/Xorg_libXfixes.v6.0.1.x86_64-linux-musl.tar.gz"
[[Xorg_libXfixes]]
arch = "x86_64"
git-tree-sha1 = "6f42150a01331cdb1f7574ae0e73bc4bfe4dd71c"
os = "freebsd"

    [[Xorg_libXfixes.download]]
    sha256 = "4049c78f6e0b185e191ed2f6c4cda5d7c2903203e53d1636cef5cba962c2414a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.1+0/Xorg_libXfixes.v6.0.1.x86_64-unknown-freebsd.tar.gz"
