[[Xorg_libXfixes]]
arch = "armv7l"
git-tree-sha1 = "25fcb9dec5fc475c76912d03d6bb2187167207fd"
libc = "glibc"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "8f5cfb838929be6a2bb7e0370b516491f1866d9de8fb6f706195a9f8dd1c27d7"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v5.0.3+2/Xorg_libXfixes.v5.0.3.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXfixes]]
arch = "i686"
git-tree-sha1 = "ea0d3344145779dadb981c9c7f8d6b5c5705560d"
libc = "musl"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "f43485fa8c4cd49621b90bddf94dbf0d8f7c6db6de3dd711b3b0a2b934a37af3"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v5.0.3+2/Xorg_libXfixes.v5.0.3.i686-linux-musl.tar.gz"
[[Xorg_libXfixes]]
arch = "aarch64"
git-tree-sha1 = "28b91099cae6da1f511b3c860b47538c039d1a73"
libc = "glibc"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "9dc7ecf4b8cc462daa917d5e3ddd37ddcfd5ec9b0421a16a1b77d51ed551e8be"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v5.0.3+2/Xorg_libXfixes.v5.0.3.aarch64-linux-gnu.tar.gz"
[[Xorg_libXfixes]]
arch = "armv7l"
git-tree-sha1 = "17f80a6d4dc5cca180c265387e108e939302ac8e"
libc = "musl"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "5f9cc8b9d6c8b933855d9b288594bbf5884e27bcd1d8bc3b6b8a7495c7130e90"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v5.0.3+2/Xorg_libXfixes.v5.0.3.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libXfixes]]
arch = "aarch64"
git-tree-sha1 = "0e7fc056e7007b9968a6bf792a40620af4f7acc7"
libc = "musl"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "351e36908ecf3090f8dc56b68dad58a6f8ee290d1b84d380bfc12e78e00fa08b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v5.0.3+2/Xorg_libXfixes.v5.0.3.aarch64-linux-musl.tar.gz"
[[Xorg_libXfixes]]
arch = "x86_64"
git-tree-sha1 = "4a086622e5b1d56934a28fac27a17992f28969e1"
os = "freebsd"

    [[Xorg_libXfixes.download]]
    sha256 = "5caf4cbe2837929110f9e09eb961d4eede08d240cbc4c9e3778e5b466aabbcb2"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v5.0.3+2/Xorg_libXfixes.v5.0.3.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_libXfixes]]
arch = "i686"
git-tree-sha1 = "169d1705c174e60d600621afed49e2b8e260600e"
libc = "glibc"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "e7ffc1ad20578a04b81ff59428f3dafa95282c63eb71f38e255f200952ee6b05"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v5.0.3+2/Xorg_libXfixes.v5.0.3.i686-linux-gnu.tar.gz"
[[Xorg_libXfixes]]
arch = "x86_64"
git-tree-sha1 = "504591c872277b4ddff1d29ece500eb4ca6865ee"
libc = "musl"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "843a892d5cdc34212949350921fd0f8fca450ccf622912c01191b84fe1fe7cfe"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v5.0.3+2/Xorg_libXfixes.v5.0.3.x86_64-linux-musl.tar.gz"
[[Xorg_libXfixes]]
arch = "x86_64"
git-tree-sha1 = "b509ac76ce4554a449522e424ec8f05ef52a6a78"
libc = "glibc"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "ba31959eb8931b3d91d6a1856c9d76df43f4212c4865472f3337f3c4aa05c26f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v5.0.3+2/Xorg_libXfixes.v5.0.3.x86_64-linux-gnu.tar.gz"
[[Xorg_libXfixes]]
arch = "powerpc64le"
git-tree-sha1 = "a3ce54a628107863d39b8062ba73fc5d4ac5436d"
libc = "glibc"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "651faf86828eb81f2d2c41d2f4d77393e31a57de7c4a57c2ecd1f023e47df2db"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v5.0.3+2/Xorg_libXfixes.v5.0.3.powerpc64le-linux-gnu.tar.gz"
