[[Xorg_libXfixes]]
arch = "aarch64"
git-tree-sha1 = "9ed009b75a71b17918dd6d5995110600b428773a"
libc = "glibc"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "c53ab8080cc6cc2523688f573b617ba44e7cfb2c65a1b6f69399c77cc3e7fc48"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.0+0/Xorg_libXfixes.v6.0.0.aarch64-linux-gnu.tar.gz"
[[Xorg_libXfixes]]
arch = "aarch64"
git-tree-sha1 = "05d677a7a99c2af3357b1622a2f67345b84f54e9"
libc = "musl"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "48e0464cd0495517ecc71bd3317015a66cf4c9ebe8dbdc2e04ee9207149009e5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.0+0/Xorg_libXfixes.v6.0.0.aarch64-linux-musl.tar.gz"
[[Xorg_libXfixes]]
arch = "aarch64"
git-tree-sha1 = "981f6d84dea131dc12c1d03bacd5552080b8a845"
os = "freebsd"

    [[Xorg_libXfixes.download]]
    sha256 = "4135dd063d48265c707059f8889a73494f42f2cb325ae73bf2e7aacff398293e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.0+0/Xorg_libXfixes.v6.0.0.aarch64-unknown-freebsd.tar.gz"
[[Xorg_libXfixes]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a5fd134a8e5ffea08e356218c1061317d9cecce6"
libc = "glibc"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "67918b0932d415b1d77ddec54316c653c1653d721fe4d241de57fe70a4c64cf4"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.0+0/Xorg_libXfixes.v6.0.0.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_libXfixes]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3c1d45f8c7025f13de193ad17fcb0c2f76c56ddb"
libc = "musl"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "c9de35d9ee5cf0298850d6fa640fce50c59b58094cb6c2a9ba29cf45b9a5c4da"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.0+0/Xorg_libXfixes.v6.0.0.armv6l-linux-musleabihf.tar.gz"
[[Xorg_libXfixes]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7fbde0ab1863fa4173c5565f873174bd57997979"
libc = "glibc"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "3ea79739ca6fc8bbddf30f4e098f93e58c2f96264b0a2de8d9abcb91d6d7c6cb"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.0+0/Xorg_libXfixes.v6.0.0.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXfixes]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b225c5fad5af47b47fd3d93532198bf4e39f81b1"
libc = "musl"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "de423b4db6616983ab8bb500ea471db964fca8dbc61136678986a339db42cf82"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.0+0/Xorg_libXfixes.v6.0.0.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libXfixes]]
arch = "i686"
git-tree-sha1 = "efb90e4c16790a1956d5d4fe372657acca0505fb"
libc = "glibc"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "938fa1d67f334871ecb91a06b06551644e2425601d88cb101a85e647c75f76a2"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.0+0/Xorg_libXfixes.v6.0.0.i686-linux-gnu.tar.gz"
[[Xorg_libXfixes]]
arch = "i686"
git-tree-sha1 = "df5a5091b8e4152efcf81b8b7e8e9dea8f2fac74"
libc = "musl"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "6ed0ebc109c70c0496975cc57aea83446f075444e0512d1d50e03d8b74cdec89"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.0+0/Xorg_libXfixes.v6.0.0.i686-linux-musl.tar.gz"
[[Xorg_libXfixes]]
arch = "powerpc64le"
git-tree-sha1 = "91d97157c28a0a9ac7e586f25de0c76e7873185c"
libc = "glibc"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "d7655bb51db13f7ff33c8ffddf96338e08ede0bf2859ecc07e6fe8033bb7c8c8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.0+0/Xorg_libXfixes.v6.0.0.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libXfixes]]
arch = "x86_64"
git-tree-sha1 = "b9b762dad2f49b75527e933ac66eea5af4cc8a30"
libc = "glibc"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "1c32f31819f133f3a75980e7e9b6daa55eb11eeca33aae2392793005074f43f3"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.0+0/Xorg_libXfixes.v6.0.0.x86_64-linux-gnu.tar.gz"
[[Xorg_libXfixes]]
arch = "x86_64"
git-tree-sha1 = "648f0946e0600c09bd956b4f7dadb27c8d65b6c3"
libc = "musl"
os = "linux"

    [[Xorg_libXfixes.download]]
    sha256 = "df2687001317cbd6c6110bb555c86b62b6006339101aaafee9162407c4cdf87d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.0+0/Xorg_libXfixes.v6.0.0.x86_64-linux-musl.tar.gz"
[[Xorg_libXfixes]]
arch = "x86_64"
git-tree-sha1 = "54832cea7e2a9f1ac955c977f20fa830e15537d8"
os = "freebsd"

    [[Xorg_libXfixes.download]]
    sha256 = "69f64390740550eeab438712dc60448c84c66bcc7fedcd11989c858a45f3f6d1"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v6.0.0+0/Xorg_libXfixes.v6.0.0.x86_64-unknown-freebsd.tar.gz"
